version: 2
jobs:
  build:
    docker: 
    - image: circleci/php:7.1-apache-stretch-browsers

    steps:  
    - checkout


    - restore_cache:
        keys:
        - v1-php-vendor-{{ checksum "composer.lock" }}
        - v1-php-vendor-

    - run: composer install --no-scripts

    - save_cache: 
        key: v1-php-vendor-{{ checksum "composer.lock" }}
        paths:
        - vendor
          

    - run: composer install
    - run: bin/phpunit  
